### ISSUE TITLE
Gnome 43 Incompatibility

### ISSUE THREAD

**Issue by imtheleviathan** [marcinjakubowski/notification-position-reloaded#13]
![Screenshot from 2022-11-05 20-05-51](https://user-images.githubusercontent.com/91233310/200149249-d9973d6c-94de-4e11-aaaf-50e70a722686.png)
 
GNOME 43 update broke compatibility, not too urgent but I do really like the extension and would like to see it work on 43. :+1:

**Comment by PHLAK** [comment]
I tried manually editing the `metadata.json` file locally (and restarting the extension) to test if it even worked on GNOME 43 but when I enabled no notifications would show up on screen at all. They would still show up in the notification "bucket" you can get to by clicking the date/time in the top bar.

**Comment by bbbenji** [comment]
Defining 43 in `metadata.json` manually, worked for me!

**Comment by PHLAK** [comment]
Yeah, it's working for me too after a reboot.

**Comment by piotrd** [comment]
There is a PR that should make the extension work again https://github.com/marcinjakubowski/notification-position-reloaded/pull/11. It got merged, but for some reason not released :thinking:

**Comment by marcinjakubowski** [comment]
Yeah sorry about that, I will take care of it this week.

**Comment by LeSnake04** [comment]
The Gnome extension site still says this extension doesn't support gnome 43

**Comment by marcinjakubowski** [comment]
The new version just got released, sorry for the delay.
