### ISSUE TITLE
[Feature Request] Add GNOME 44 Support

### ISSUE THREAD

**Issue by git-Hmmm** [marcinjakubowski/notification-position-reloaded#15]
Please add support for GNOME 44 to ensure compatibility with the latest version of GNOME and provide users with access to new features and improvements.

**Comment by git-Hmmm** [comment]
I have disabled version validation and it appears to be functioning correctly. It seems that adding the version to the manifest file is the only necessary step.

**Comment by fedelibre** [comment]
@marcinjakubowski Can you please bump the GNOME version?

Tired of bumping `~/.local/share/gnome-shell/extensions/notification-banner-reloaded@marcinjakubowski.github.com/metadata.json` on all my computers :-)

**Comment by marcinjakubowski** [comment]
just released
