### ISSUE TITLE
Extension settings not working

### ISSUE THREAD

**Issue by neriff** [marcinjakubowski/notification-position-reloaded#2]
Ubuntu 20.04

Notification settings not working
![Screenshot from 2021-12-23 14-27-17](https://user-images.githubusercontent.com/36342757/147240592-54741922-b5ec-4004-a444-02b3ead61324.png)
.

**Comment by marcinjakubowski** [comment]
are you able to expand the technical details? also, which gnome shell version are you using?

**Comment by marcinjakubowski** [comment]
I was able to replicate it in an Ubuntu 20.04 VM, I'll try my best to find the root cause for this.

**Comment by marcinjakubowski** [comment]
new version published on [extensions.gnome.org](https://extensions.gnome.org/extension/4651/notification-banner-reloaded/)
