### ISSUE TITLE
[Bug] Notification's close button placement does not follow system preference

### ISSUE THREAD

**Issue by hyuri** [marcinjakubowski/notification-position-reloaded#20]
Hi! Great extension!

The close button in the notifications aren't following my system preference. I have my window buttons placed to the left instead of the right, but the close button in the notifications are still placed on the right side.

**Comment by marcinjakubowski** [comment]
I don't think I'm touching any of the code that actually displays a notification, do you get the close button where you'd expect it without the extension? If so and it's actually the extension that causing it, what do I need to change locally to reproduce this behavior (as in how did you change the placement of the buttons)?

**Comment by hyuri** [comment]
Now that you mentioned it, I think the close button on the notification bubbles has never followed the system settings, even before installing this extension.

So I guess it's more of a Gnome Shell bug. Or a [missing] feature request here.

As for your last question, regarding how to change the placement of the buttons:
I changed it using Gnome Tweaks, in `Window Titlebars --> Titlebar Buttons --> Placement --> Left`.

**Comment by marcinjakubowski** [comment]
not an extension issue
