### ISSUE TITLE
[Feature Request] Add GNOME 45 Support

### ISSUE THREAD

**Issue by git-Hmmm** [marcinjakubowski/notification-position-reloaded#21]
GNOME 45 is in beta now, Please add support for it to ensure compatibility with the latest version of GNOME and provide users with access to new features and improvements.

**Comment by darkdragon-001** [comment]
Here you find the official [porting guide](https://gjs.guide/extensions/upgrading/gnome-shell-45.html#esm).

**Comment by sagitariozod** [comment]
Please upgrade to gnome 45.
I have tried with porting guide but it not work.

Tanks.

**Comment by BloodyIron** [comment]
It's November and this hasn't been updated to Gnome 45? Come on :/

**Comment by marcinjakubowski** [comment]
> It's November and this hasn't been updated to Gnome 45? Come on :/

Oh sorry, did I miss a pull request? Come on.

I'm on 44 specifically because a lot of extensions I've been using myself have not been updated to 45 and I can't afford to disrupt my own workflow by upgrading. I have a job that I need to be able to do. 

I actually have the actual extension going on 45, but can't get preferences widget to work, seems it needs to be rewritten using Adw. Maybe you could volunteer that? It's a bunch of not-so-fun UI work, but shouldn't be difficult.

**Comment by marcinjakubowski** [comment]
Here's v45 https://github.com/marcinjakubowski/notification-position-reloaded/tree/v45 branch for anyone interested in picking the prefs up.

**Comment by sagitariozod** [comment]
Good morning.
Thanks for the branch to Gnome 45, although the preferences don't work, it's enough for me, I make the adjustments in gconf.
I would like to collaborate, but I do not control adw programming.
Thank you so much.

In case it helps, the error that appears in the preferences is the following.

`TypeError: Object is of type Gtk.Grid - cannot convert to AdwPreferencesGroup

Stack trace:
  fillPreferencesWindow@file:///............../.local/share/gnome-shell/extensions/notification-banner-reloaded@marcinjakubowski.github.com/prefs.js:179:14
  _loadPrefs@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:36:18
  async*_init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:21:14
  ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:12:4
  OpenExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:139:33
  async*_handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:373:35
  _wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:408:34
  _init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34`

**Comment by marcinjakubowski** [comment]
Yeah I know prefs don't work, I don't know how to inject old style Gtk prefs into the new window and rewriting them into Adw is a lot. I might do it over the weekend.

**Comment by sagitariozod** [comment]
Thank you very much for your time.

**Comment by marcinjakubowski** [comment]
Thanks to @mannjani for the implemention, merged and released (pending review but that doesn't usually take long)

**Comment by sagitariozod** [comment]
Thank you very much for the update.

I have installed the @mannjani fork with the notification test button and everything works fine.

Greetings.
