### ISSUE TITLE
Add a Send Test Notification button to Settings

### ISSUE THREAD

**Issue by biro456** [marcinjakubowski/notification-position-reloaded#3]
So we can test configuration changes without having to wait for an actual notification.

**Comment by marcinjakubowski** [comment]
I did try to do it, but for some reason the notifications do not get raised when sent from the extension configuration pane. I'll look more into it as I have another idea, but I can suggest using `notify-send hello` from the terminal to test (that's what I did myself).

**Comment by demizer** [comment]
Workaround until this is implemented. Test can be done using notify-send:

```
notify-send foo bar
```
