### ISSUE TITLE
Misplacement in multi-screen / multi-resolution setup

### ISSUE THREAD

**Issue by theDevelopper** [marcinjakubowski/notification-position-reloaded#6]
Does not properly place notifications in a multi-screen setup with different screen sizes / resolutions.

I have placed my notifications in the bottom right corner. Notifications are always shown on the same screen, the primary screen, but placement is calculated based on the screen with active window. If the active window is "smaller" than the primary screen showing the notification, then it is placed not within the corner but somewhere in the lower right area matching the wrong screen size.

Rather than taking the resolution of the current screen with `get_current_monitor` maybe it should use the primary screen instead?

This is the current code:
```
const getMessageTraySize = () => ({ width, height } = Main.layoutManager.getWorkAreaForMonitor(global.display.get_current_monitor()));
```

**Comment by martindmtrv** [comment]
Having the same issue on my end as well, I think we can just change it to `global.display.get_primary_monitor()` to fix! I'll give it a go and maybe put out a PR to fix!
